{
 "title": "Mainnet monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ADNL Peers",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  label_join(adnl_peer, \"socket_addr\", \":\", \"ip\", \"port\") * on(socket_addr) group_left validator_ip,\n  \"latitude\", \"$1\", \"adjusted_latitude\", \"(.+)\"),\n  \"longitude\", \"$1\", \"adjusted_longitude\", \"(.+)\")"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  label_join(adnl_peer, \"socket_addr\", \":\", \"ip\", \"port\") unless label_join(adnl_peer, \"socket_addr\", \":\", \"ip\", \"port\") * on(socket_addr) group_left validator_ip,\n  \"latitude\", \"$1\", \"adjusted_latitude\", \"(.+)\"),\n  \"longitude\", \"$1\", \"adjusted_longitude\", \"(.+)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "options": {
    "content": "## Everscale monitoring\n\nExporter can be self-hosted by anyone: [GitHub repo](https://github.com/broxus/everscale-monitoring). \n\nIf you have any suggestions or noticed some errors - please fill an issue on github. \n\nAlerts channel in Telegram: [@everscale_monitoring](https://t.me/everscale_monitoring)\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "MC Software Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (software_version) (increase(frmon_mc_software_version[5m])) / ignoring(software_version) group_left sum(increase(frmon_mc_software_version[5m]))",
     "legendFormat": "{{software_version}}"
    }
   ]
  },
  {
   "title": "SC Software Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (software_version) (increase(frmon_sc_software_version[1m])) / ignoring(software_version) group_left sum(increase(frmon_sc_software_version[1m]))",
     "legendFormat": "{{software_version}}"
    }
   ]
  },
  {
   "title": "Network load",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks rate 5m",
   "type": "timeseries",
   "description": "Speed of applying of blocks over last 5 minutes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "b/s" } },
   "targets": [
    {
     "expr": "rate(frmon_aggregate{collection=\"blocks\"}[5m])",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Messages rate 5m",
   "type": "timeseries",
   "description": "Speed of applying of messages over last 5 minutes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(frmon_aggregate{collection=\"messages\"}[5m])",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Transactions rate 5m",
   "type": "timeseries",
   "description": "Speed of applying of transactions over last 5 minutes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "rate(frmon_aggregate{collection=\"transactions\"}[5m])",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Shardchains",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of shards",
   "type": "timeseries",
   "description": "Number of shards (threads) in the network compared to configured in the network configuration",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "🔀" } },
   "targets": [
    { "expr": "frmon_mc_shards", "legendFormat": "Reported" },
    {
     "expr": "sum(present_over_time(frmon_sc_seqno[1m]))",
     "legendFormat": "Observed (1m)"
    }
   ]
  },
  {
   "title": "Shard rates",
   "type": "state-timeline",
   "description": "State timeline of shards block speed over the last 5 minutes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "targets": [
    { "expr": "rate(frmon_sc_seqno[5m])", "legendFormat": "{{shard}}" }
   ]
  },
  {
   "title": "Shard transactions",
   "type": "state-timeline",
   "description": "Utilization of shardchains and masterchain",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "avg_over_time(frmon_sc_avgtrc[5m])",
     "legendFormat": "{{shard}}"
    },
    {
     "expr": "avg_over_time(frmon_mc_avgtrc[5m]) - 5",
     "legendFormat": "mc"
    }
   ]
  },
  {
   "title": "R-Node front statistics",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard lag",
   "type": "timeseries",
   "description": "Amount of time shardchains are behind masterchain",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "frmon_mc_seqno - frmon_mc_shard_seqno",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Masterchain block intervals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "spb" } },
   "targets": [
    { "expr": "1/rate(frmon_mc_seqno[5m])", "legendFormat": "M1" }
   ]
  },
  {
   "title": "Avg shardchain block rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "b/s" } },
   "targets": [
    {
     "expr": "avg(delta(frmon_sc_seqno[5m]) / 300) by (endpoint)",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Information collected",
   "type": "timeseries",
   "description": "Time difference between now and when monitoring service collected information from the blockchain",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s ago" } },
   "targets": [
    {
     "expr": "clamp_min(time() - frmon_updated - 10, 0)",
     "legendFormat": "M1"
    }
   ]
  },
  {
   "title": "Avg TX / 50 blocks",
   "type": "timeseries",
   "description": "MC: Masterchain, SC: Shardchain (average)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "tpb" } },
   "targets": [
    { "expr": "frmon_mc_avgtrc", "legendFormat": "MC" },
    { "expr": "sum(frmon_sc_avgtrc)", "legendFormat": "SC" }
   ]
  },
  {
   "title": "Last block delta",
   "type": "timeseries",
   "description": "MC: Masterchain, SC: Shardchain (average),\n\nmSC: Shardchain (maximum)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "frmon_updated - frmon_mc_utime", "legendFormat": "MC" },
    {
     "expr": "frmon_updated - on () avg(frmon_sc_utime)",
     "legendFormat": "avg SC"
    },
    {
     "expr": "frmon_updated - on () min(frmon_sc_utime)",
     "legendFormat": "max SC"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State of elections",
   "type": "timeseries",
   "description": "Status and participant amount of the elections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(elections_stake_value) by (net)",
     "legendFormat": "Participants"
    },
    { "expr": "config_min_validators", "legendFormat": "Required" },
    {
     "expr": "count(skcl_observer_to_return > 0) by (net)",
     "legendFormat": "Returns"
    },
    { "expr": "elections_elect_at > bool 0", "legendFormat": "Elections" }
   ]
  },
  {
   "title": "Private Overlays",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "(\n    count(overlay_entry) by (overlay_id)\n) \n    + on(overlay_id) group_right(catchain_seqno) \n(\n    0 * label_replace(label_join(overlay, \"shard_full\", \":\", \"workchain\", \"shard\"), \"shard_full\", \"$1...\", \"shard_full\", \"(.*)\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Validators",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((\n    validator / 1000000000\n) + on(pubkey) group_left(socket_addr) (0 * validator_ip))\nor on(pubkey) (validator / 1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "((validator * 0) + on(pubkey) (count by(pubkey) ((overlay_entry * on(overlay_id) group_left overlay{workchain=\"-1\"}) and on(pubkey) (overlay_entry * 0)))) or on(pubkey) (validator * 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(validator + on(pubkey) group_left(shard_full) overlay_entry * on(overlay_id) group_left(shard_full) label_replace(overlay{workchain=\"0\"}, \"shard_full\", \"0:$1...\", \"shard\", \"(.*)\")) or on(pubkey) validator",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}