[package]
name = "geoip-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
bincode = "1.3"
csv = "1.1"
env_logger = "0.9"
futures = "0.3"
indicatif = "0.16.2"
log = "0.4"
public-ip = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tikv-jemalloc-sys = { version = "0.4", features = ["unprefixed_malloc_on_supported_platforms", "background_threads"] }
tikv-jemallocator = "0.4"
tokio = { version = '1', features = ["rt-multi-thread", "sync", "macros", "parking_lot"] }

rocksdb = { git = "https://github.com/Rexagon/rust-rocksdb.git", features = ["lz4", "jemalloc"], default-features = false }

ed25519-dalek = { git = "https://github.com/broxus/ed25519-dalek.git" }

global-config = { git = "https://github.com/broxus/ton-indexer.git" }
tiny-adnl = { git = "https://github.com/broxus/tiny-adnl.git" }
