[package]
name = "geoip-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
env_logger = "0.9"
futures = "0.3"
log = "0.4"
public-ip = "0.2"
rand = "0.8"
tokio = { version = '1', features = ["rt-multi-thread", "sync", "macros", "parking_lot"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

ed25519-dalek = { git = "https://github.com/broxus/ed25519-dalek.git" }

global-config = { git = "https://github.com/broxus/ton-indexer.git" }
tiny-adnl = { git = "https://github.com/broxus/tiny-adnl.git" }
